-- Deprecated.
-- External resource storage has been normalized into structured tables.
-- Please use the Python scripts below instead of importing SQL directly:
--
--   python init_db.py
--   python seed_data.py
--
-- For a destructive rebuild of schema and demo data:
--
--   python reset_db.py --confirm RESET
